setup:
	dependencies/Scripts/pip.exe install -r requirements.txt

run:
	dependencies/Scripts/python.exe main.py

test:
    # -v for verbose
    # -s for stdout
	dependencies/Scripts/python.exe -m pytest -v -s tests
